base:
  debug: true
  print_freq: 100
  num_workers: 8
  seed: 42
  target_size: 29
  target_cols: "all"
  n_fold: 4
  trn_fold: [0]
  train: True

model:
  model_name: "efficientnet_b3"
  size: 480
  scheduler: "CosineAnnealingLR"
  T_max: 6
  lr: 1e-3
  min_lr: 1e-6
  batch_size: 16
  weight_decay: 1e-6
  gradient_accumulation_steps: 1
  max_grad_norm: 1000
  pretrained: "imagenet"

  epochs: 15

wandb:
  use: true
  project: "rfmd-exp-1"
  name: "efficientnet_b3_imagenet"
  tags: [
          "rfmd",
          "efficientnet",
          "efficientnet_b3"
  ]

#wandb:
#  use: true
#  project: "rfmd-exp-1"
#  name: "seresnet50"
#  tags: [
#          "rfmd",
#          "seresnet",
#          "seresnet50"
#  ]
