base:
  debug: true
  print_freq: 100
  num_workers: 8
  seed: 42
  target_size: 29
  target_cols: "all"
  n_fold: 4
  trn_fold: [0]
  train: True

model:
  model_name: "efficientnet_b3"
  size: 480
  scheduler: "CosineAnnealingLR"
  T_max: 6
  lr: 1e-3
  min_lr: 1e-6
  batch_size: 16
  weight_decay: 1e-6
  gradient_accumulation_steps: 1
  max_grad_norm: 1000
  pretrained: true

  epochs: 15

wandb:
  use: true
  project: "rfmd-exp-1"
  name: "seresnext50_32x4d"
  tags: [
          "rfmd",
          "seresnext",
          "seresnext50_32x4d"
  ]
