base:
  train_path: '../data/train_p_1'
  test_path: '../data/eval_p_1'
  print_freq: 100
  num_workers: 8
  seed: 42
  target_size: 29
  target_cols: [
      "Disease_Risk", "DR", "ARMD", "MH", "DN",
      "MYA", "BRVO", "TSLN", "ERM", "LS", "MS",
      "CSR", "ODC", "CRVO", "TV", "AH", "ODP",
      "ODE", "ST", "AION", "PT", "RT", "RS", "CRS",
      "EDN", "RPEC", "MHL", "RP", "OTHER"
  ]
  n_fold: 4
  trn_fold: [0]
  train: True
  oof: False

split:
  name: "MultilabelStratifiedKFold"
  param: {
           "n_splits": 4,
           "shuffle": True,
           "random_state": 1212
  }

model:
  model_name: "tf_efficientnet_b0_ns"
  size: 224  # 480
  batch_size: 64
  pretrained: true
  epochs: 15

loss:
  name: "BCEFocalLoss"
  param: {}

optimizer:
  name: "AdamW"
  param: {
           "lr": 1e-3,
           "weight_decay": 1e-6,
           "amsgrad": False
  }

scheduler:
  name: "CosineAnnealingLR"
  param: {
            "T_max": 6,
            "eta_min": 0,
            "last_epoch": -1
  }

wandb:
  use: true
  project: "rfmd-exp-2"
  name: "focal-1"
  tags: [
          # "tf_efficientnet_b0_ns",
          "tf_efficientnet_b0_ns",
          "focal_loss"
          # "aug_7"
  ]
