base:
  train_path: '../data/train_p_ietk'
  test_path: '../data/eval_p_ietk'
  extra_path: "../extra/train_p_1"
  print_freq: 100
  num_workers: 8
  seed: 42
#  target_size: 1
#  target_cols: ["TV"]
  target_size: 29
  target_cols: [
      "ST"
  ]
  n_fold: 4
  trn_fold: [0]
  train: True
  oof: False

split:
  #name: "StratifiedKFold"
  name: "StratifiedKFold"
  param: {
           "n_splits": 4,
           "shuffle": True,
           "random_state": 1212
  }

model:
  model_name: "tf_efficientnet_b0_ns"
  #model_name: "dm_nfnet_f0"
  size: 224  # 480
  batch_size: 32
  pretrained: true
  epochs: 15
  gem: false  # nfnetのときはfalse

loss:
  name: "BCEFocalLoss"
  param: {}

optimizer:
  name: "AdamW"
  # base: "AdamW"#
  param: {
           "lr": 5e-3,
           # "weight_decay": 1e-6,
           # "amsgrad": False
  }

scheduler:
  name: "CosineAnnealingLR"
  param: {
            "T_max": 10,
            "eta_min": 0,
            "last_epoch": -1
  }

wandb:
  use: false
  project: "exp6"
  name: "ST"
  tags: [
          # "tf_efficientnet_b0_ns",
          "nfnet_f0",
          # "focal_loss"
          # "aug_7"
  ]
